[project]
name = "mmvc-trainer-v13"
version = "1.3.0"
requires-python = "==3.8.20"
dependencies = [
    "pyopenjtalk",
    "cython==0.29.21",
    "librosa==0.8.0",
    "matplotlib==3.3.1",
    "phonemizer==2.2.1",
    "scipy",
    "tensorboard==2.3.0",
    "torch==1.13.1+cu116",
    "torchvision==0.14.1+cu116",
    "torchaudio==0.13.1+cu116",
    "unidecode==1.1.1",
    "retry",
    "tqdm",
    "resampy==0.2.2",
    "psutil",
    "protobuf==3.20.3",
    "numpy==1.23.5",
    "onnx==1.13.1",
]

[tool.uv]
package = false

build-constraint-dependencies = [
    "cython==3.0.12",
]

[[tool.uv.index]]
name = "pytorch-cu116"
url = "https://download.pytorch.org/whl/cu116"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu116" }
torchvision = { index = "pytorch-cu116" }
torchaudio = { index = "pytorch-cu116" }
